Updated handling of disks and added new commands to help

diff --git a/kvmadm b/kvmadm
--- a/kvmadm
+++ b/kvmadm
@@ -4,21 +4,21 @@ VMDISK_ROOT=/dev/zvol/rdsk/$VM_POOL
 NIC_TYPE=virtio
 HDD_TYPE=virtio
 BASE_DIR=/etc/vms
-RUN_PATH=/tmp
+  RUN_PATH=/tmp
 
 function rand_nic() {
-	printf 'DE:AD:%02X:%02X:%02X:%02X\n' $((RANDOM%257)) $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256))
+  printf 'DE:AD:%02X:%02X:%02X:%02X\n' $((RANDOM%257)) $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256))
 }
 
 function new_vm() {
-	NAME=$1
-	if [ -f "$BASE_DIR/$NAME" ]; then
-		echo "VM $NAME already exists"
-		exit 1
-	fi
-	MAC=`rand_nic`
-	ID=`next_id`
-	cat > "$BASE_DIR/$NAME" <<EOF 
+  NAME=$1
+  if [ -f "$BASE_DIR/$NAME" ]; then
+    echo "VM $NAME already exists"
+    exit 1
+  fi
+  MAC=`rand_nic`
+  ID=`next_id`
+  cat > "$BASE_DIR/$NAME" <<EOF 
 NAME=$NAME
 DISK0_TYPE=hda
 DISK0_FILE=
@@ -36,25 +36,25 @@ EOF
 }
 
 function check_vm() {
-	if [ ! -f "$BASE_DIR/$1" ]; then
-		echo "VM $1 does not exist."
-		exit 1
-	fi
+  if [ ! -f "$BASE_DIR/$1" ]; then
+    echo "VM $1 does not exist."
+    exit 1
+  fi
 }
 
 function show_vm() {
-	VM=$1
-	if [ -z "$(vm_status $VM)" ]; then
-		STATUS="offline"
-	else
-		STATUS="online"
-	fi
-	if [ "$(vm_val $VM ACTIVE)" == 0 ]; then
-		STATUS="inactive"
+  VM=$1
+  if [ -z "$(vm_status $VM)" ]; then
+    STATUS="offline"
+  else
+    STATUS="online"
+  fi
+  if [ "$(vm_val $VM ACTIVE)" == 0 ]; then
+    STATUS="inactive"
   fi
 
 
-	cat <<EOF
+  cat <<EOF
 VM Status - $(vm_val $VM NAME) 
 =================
 
@@ -75,32 +75,32 @@ IO
 ISO: $(vm_val $VM ISO)
 HDD: $(vm_val $VM DISK)
 EOF
-	DISK_ID=0
-	while [ "$(vm_val $VM "DISK${DISK_ID}_TYPE")" ]; do
-		TYPE=$(vm_val $VM "DISK${DISK_ID}_TYPE")
-		FILE=$(vm_val $VM "DISK${DISK_ID}_FILE")
-		cat <<EOF
+  DISK_ID=0
+  while [ "$(vm_val $VM "DISK${DISK_ID}_TYPE")" ]; do
+    TYPE=$(vm_val $VM "DISK${DISK_ID}_TYPE")
+    FILE=$(vm_val $VM "DISK${DISK_ID}_FILE")
+    cat <<EOF
 
 Disk $DISK_ID
 ============
 Type: $TYPE
 File: $FILE
 EOF
-	DISK_ID=$(expr $DISK_ID + 1)
-	done
-	NIC_ID=0 
-	while [ "$(vm_val $VM "NIC${NIC_ID}_VNIC")" ]; do
-		VNIC=$(vm_val $VM "NIC${NIC_ID}_VNIC")
-		MAC=$(vm_val $VM "NIC${NIC_ID}_MAC")
-		TYPE=$(vm_val $VM "NIC${NIC_ID}_TYPE")
-		if [ -z "${TYPE}" ]; then
-			TYPE="virtio"
-		fi
-		VLAN=$(vm_val $VM "NIC${NIC_ID}_VLAN")
-		if [ -z "${VLAN}" ]; then
-			VLAN="0"
-		fi
-		cat <<EOF
+  DISK_ID=$(expr $DISK_ID + 1)
+  done
+  NIC_ID=0 
+  while [ "$(vm_val $VM "NIC${NIC_ID}_VNIC")" ]; do
+    VNIC=$(vm_val $VM "NIC${NIC_ID}_VNIC")
+    MAC=$(vm_val $VM "NIC${NIC_ID}_MAC")
+    TYPE=$(vm_val $VM "NIC${NIC_ID}_TYPE")
+    if [ -z "${TYPE}" ]; then
+      TYPE="virtio"
+    fi
+    VLAN=$(vm_val $VM "NIC${NIC_ID}_VLAN")
+    if [ -z "${VLAN}" ]; then
+      VLAN="0"
+    fi
+    cat <<EOF
 
 Network Adapter $NIC_ID
 =======================
@@ -109,234 +109,234 @@ VNIC: $VNIC
 MAC:  $MAC
 VLAN: $VLAN
 EOF
-		NIC_ID=`expr $NIC_ID + 1`
-	done
+    NIC_ID=`expr $NIC_ID + 1`
+  done
 }
 function start_vm() {
-	VM=$1
-	NAME=$(vm_val $VM NAME)
-	if vm_status $VM; then
-		echo "VM $NAME already running." 
-		exit 1
-	fi
-	if [ "$(vm_val $VM ACTIVE)" == "0" ]; then
-		echo "VM is deactivated."
-		exit 1
+  VM=$1
+  NAME=$(vm_val $VM NAME)
+  if vm_status $VM; then
+    echo "VM $NAME already running." 
+    exit 1
   fi
-	echo "Starting VM $NAME"
-	PARAMS="-enable-kvm -nographic -no-hpet -smp $(vm_val $VM CPUS)"
-	PARAMS="${PARAMS} -monitor unix:${RUN_PATH}/kvm.${NAME}.mon,server,nowait"
-	NIC_ID=0 
-	while [ "$(vm_val $VM "NIC${NIC_ID}_VNIC")" ]; do
-		VNIC=$(vm_val $VM "NIC${NIC_ID}_VNIC")
-		MAC=$(vm_val $VM "NIC${NIC_ID}_MAC")
-		TYPE=$(vm_val $VM "NIC${NIC_ID}_TYPE")
-		if [ -z "${TYPE}" ]; then
-			TYPE="virtio"
-		fi
-		VLAN=$(vm_val $VM "NIC${NIC_ID}_VLAN")
-		if [ -z "${VLAN}" ]; then
-			VLAN="0"
-		fi
-		PARAMS="${PARAMS} -net nic,vlan=${VLAN},name=net${NIC_ID},model=${TYPE},macaddr=${MAC}"
-  	PARAMS="${PARAMS} -net vnic,vlan=${VLAN},name=net${NIC_ID},ifname=${VNIC},macaddr=${MAC}"
-		NIC_ID=`expr $NIC_ID + 1`
-	done
-	PARAMS="${PARAMS} -m $(vm_val $VM MEM) -vnc :$(vm_val $VM ID)  -no-hpet"
-	PARAMS="${PARAMS} -chardev socket,id=serial0,path=${RUN_PATH}/kvm.${NAME}.console,server,nowait -serial chardev:serial0 $(vm_val $VM OPTS)"
+  if [ "$(vm_val $VM ACTIVE)" == "0" ]; then
+    echo "VM is deactivated."
+    exit 1
+  fi
+  echo "Starting VM $NAME"
+  PARAMS="-enable-kvm -nographic -no-hpet -smp $(vm_val $VM CPUS)"
+  PARAMS="${PARAMS} -monitor unix:${RUN_PATH}/kvm.${NAME}.mon,server,nowait"
+  NIC_ID=0 
+  while [ "$(vm_val $VM "NIC${NIC_ID}_VNIC")" ]; do
+    VNIC=$(vm_val $VM "NIC${NIC_ID}_VNIC")
+    MAC=$(vm_val $VM "NIC${NIC_ID}_MAC")
+    TYPE=$(vm_val $VM "NIC${NIC_ID}_TYPE")
+    if [ -z "${TYPE}" ]; then
+      TYPE="virtio"
+    fi
+    VLAN=$(vm_val $VM "NIC${NIC_ID}_VLAN")
+    if [ -z "${VLAN}" ]; then
+      VLAN="0"
+    fi
+    PARAMS="${PARAMS} -net nic,vlan=${VLAN},name=net${NIC_ID},model=${TYPE},macaddr=${MAC}"
+    PARAMS="${PARAMS} -net vnic,vlan=${VLAN},name=net${NIC_ID},ifname=${VNIC},macaddr=${MAC}"
+    NIC_ID=`expr $NIC_ID + 1`
+  done
+  PARAMS="${PARAMS} -m $(vm_val $VM MEM) -vnc :$(vm_val $VM ID)  -no-hpet"
+  PARAMS="${PARAMS} -chardev socket,id=serial0,path=${RUN_PATH}/kvm.${NAME}.console,server,nowait -serial chardev:serial0 $(vm_val $VM OPTS)"
   DISK_ID=0
   while [ "$(vm_val $VM "DISK${DISK_ID}_TYPE")" ]; do
     TYPE=$(vm_val $VM "DISK${DISK_ID}_TYPE")
     FILE=$(vm_val $VM "DISK${DISK_ID}_FILE")
-		case $TYPE in
-			hd?)
-				PARAMS="${PARAMS} -${TYPE} ${VMDISK_ROOT}/${FILE}"
-			;;
-			cdrom)
-				PARAMS="${PARAMS} -${TYPE} ${FILE}"
-			;;
-			*)
-			echo "Unknown disk type $TYPE, skipping disk $DISK_ID."
-			;;
-		esac
-  	DISK_ID=$(expr $DISK_ID + 1)
+    case $TYPE in
+      hd?)
+        PARAMS="${PARAMS} -${TYPE} ${VMDISK_ROOT}/${FILE}"
+      ;;
+      cdrom)
+        PARAMS="${PARAMS} -${TYPE} ${FILE}"
+      ;;
+      *)
+      echo "Unknown disk type $TYPE, skipping disk $DISK_ID."
+      ;;
+    esac
+    DISK_ID=$(expr $DISK_ID + 1)
   done
 
-  echo	qemu-system-x86_64 ${PARAMS} #> ${RUN_PATH}/kvm.${NAME}.log &
-	echo $! > ${RUN_PATH}/kvm.${NAME}.pid
+  echo  qemu-system-x86_64 ${PARAMS} #> ${RUN_PATH}/kvm.${NAME}.log &
+  echo $! > ${RUN_PATH}/kvm.${NAME}.pid
 }
 function next_id() {
-	expr `cat $BASE_DIR/* | grep "^ID=" | sed "s/^ID=//" | sort -n | tail -1` + 1
+  expr `cat $BASE_DIR/* | grep "^ID=" | sed "s/^ID=//" | sort -n | tail -1` + 1
 }
 
 function write_opt() {
-	if [ -z "$3" ]; then
-		sed -i "s/^${2}=.*//" ${BASE_DIR}/${1}
-	else	
-		if grep "^${2}=" ${BASE_DIR}/${1} > /dev/null; then
-			sed -i "s/^${2}=.*/${2}=${3}/" ${BASE_DIR}/${1}
-		else
-			echo "${2}=${3}" >> ${BASE_DIR}/${1}
-		fi
-	fi
+  if [ -z "$3" ]; then
+    sed -i "s/^${2}=.*//" ${BASE_DIR}/${1}
+  else  
+    if grep "^${2}=" ${BASE_DIR}/${1} > /dev/null; then
+      sed -i "s/^${2}=.*/${2}=${3}/" ${BASE_DIR}/${1}
+    else
+      echo "${2}=${3}" >> ${BASE_DIR}/${1}
+    fi
+  fi
 }
 
 function vm_status() {
-	PID=`cat ${RUN_PATH}/kvm.${1}.pid 2> /dev/null`
-	ps -eo pid | sed 's/ //g' | grep "^$PID$"
+  PID=`cat ${RUN_PATH}/kvm.${1}.pid 2> /dev/null`
+  ps -eo pid | sed 's/ //g' | grep "^$PID$"
 }
 
 function vm_val() {
-	if [ -f "${BASE_DIR}/${1}" ]; then
-	  echo `grep "$2=" "${BASE_DIR}/${1}" | sed "s/$2=//"`
-	fi
+  if [ -f "${BASE_DIR}/${1}" ]; then
+    echo `grep "$2=" "${BASE_DIR}/${1}" | sed "s/$2=//"`
+  fi
 }
 
 function set_opt() {
-	VM=$1
-	if [ ! -f $BASE_DIR/$VM ]
-	then
-		echo "Can't find VM $MV_CFG_PATH"
-		exit 1
-	fi
-	OPT=$2
-	case $OPT in
-		opts)
-			write_opt $VM "OPTS" "$3"
-		;;
-		active)
-			write_opt $VM "ACTIVE" "$3"
-		;;
-		cpu)
-			write_opt $VM "CPUS" "$3"
-		;;
-		mem)
-			write_opt $VM "MEM" "$3"
-		;;
-		disk)
-			if [ -f $VMDISK_ROOT/$3 ]; then
-				write_opt $VM "DISK" "$3"
-			else
-				echo "Can't find VM DISK $3"
-				echo "Plese crate it with:\nzfs create -V <size e.g. 10g> $VM_POOL/$3"
-				exit 1
-			fi
-		;;
-		iso)
-			if [ -f $3]; then
-				write_opt $VM "ISO" "$3"
-			else
-				echo "Can't find ISO file $3."
-			fi
-		;;
-		net)
-			case $4 in
-				type)
-					write_opt $VM "NIC${3}_TYPE" "$5"
+  VM=$1
+  if [ ! -f $BASE_DIR/$VM ]
+  then
+    echo "Can't find VM $MV_CFG_PATH"
+    exit 1
+  fi
+  OPT=$2
+  case $OPT in
+    opts)
+      write_opt $VM "OPTS" "$3"
+    ;;
+    active)
+      write_opt $VM "ACTIVE" "$3"
+    ;;
+    cpu)
+      write_opt $VM "CPUS" "$3"
+    ;;
+    mem)
+      write_opt $VM "MEM" "$3"
+    ;;
+    disk)
+      case $4 in
+        type)
+          if echo $5 | grep "cdrom|hd[a-d]"; then
+            write_opt $VM "DISK${3}_TYPE" $5
+          else
+            echo "No valid disk type, currently only cdrom and hda-hdd are supported"
+          fi  
+        ;;
+        file)
+          write_opt $VM "DISK${3}_FILE" $5
 				;;
-				vnic)
-					if dladm show-vnic | tail -n +2 | grep "^$5 " > /dev/null
-					then
-						write_opt $VM "NIC${3}_VNIC" "$5"
-					else
-						echo "Can't find vnic $5."
-						echo "Create it with:"
-						echo "dladm create-vnic -l <interface> $5"
-						exit 1
-					fi
-				;;
-				mac)
-					if [ "$5" == "rand" ]; then
-						write_opt $VM "NIC${3}_MAC" `rand_nic`
-					else	
-						write_opt $VM "NIC${3}_MAC" "$5"
-					fi
-				;;
-				vlan)
-					write_opt $VM "NIC${3}_VLAN" "$5"
-				;;
-				*)
-					echo "Invalid network category, valid options are: type, vnic, mac, vlan."
-				;;
-			esac
-			;;
-		*)
-			echo "Valid options are: cpu, mem, disk, iso."
-		;;
-	esac	
+        *)
+        ;;
+      esac
+    ;;
+    net)
+      case $4 in
+        type)
+          write_opt $VM "NIC${3}_TYPE" "$5"
+        ;;
+        vnic)
+          if dladm show-vnic | tail -n +2 | grep "^$5 " > /dev/null
+          then
+            write_opt $VM "NIC${3}_VNIC" "$5"
+          else
+            echo "Can't find vnic $5."
+            echo "Create it with:"
+            echo "dladm create-vnic -l <interface> $5"
+            exit 1
+          fi
+        ;;
+        mac)
+          if [ "$5" == "rand" ]; then
+            write_opt $VM "NIC${3}_MAC" `rand_nic`
+          else  
+            write_opt $VM "NIC${3}_MAC" "$5"
+          fi
+        ;;
+        vlan)
+          write_opt $VM "NIC${3}_VLAN" "$5"
+        ;;
+        *)
+          echo "Invalid network category, valid options are: type, vnic, mac, vlan."
+        ;;
+      esac
+      ;;
+    *)
+      echo "Valid options are: cpu, mem, disk, iso."
+    ;;
+  esac  
 }
 
 case $1 in
   start)
-	if [ "$2" == "all" ]; then
+  if [ "$2" == "all" ]; then
     CPWD=$PWD
-		cd $BASE_DIR
-		for vm in `ls -1`; do
-			if [ "`vm_val $vm ACTIVE`" != "0" ]; then
-				start_vm $vm
-			fi
-		done
-		cd $CPWD
-		exit 0
-	fi
-	check_vm $2
-	start_vm $2
-	;;
+    cd $BASE_DIR
+    for vm in `ls -1`; do
+      if [ "`vm_val $vm ACTIVE`" != "0" ]; then
+        start_vm $vm
+      fi
+    done
+    cd $CPWD
+    exit 0
+  fi
+  check_vm $2
+  start_vm $2
+  ;;
   list)
     CPWD=$PWD
-		cd $BASE_DIR
-	  printf "%-5s %20s %s\n" "ID" "VM" "Status"
-		for vm in `ls -1`;
-		do
-			NAME=`vm_val $vm NAME`
-			PID=`vm_status $NAME`
-			if [ -z "$PID" ]; then
-				STATE="ofline"
-			else
-				STATE="online ($PID)"
-			fi
-			ACTIVE=`vm_val $vm ACTIVE`
-			if [  "$ACTIVE" == 0 ]; then
-				STATE="inactive"
-			fi
-			printf "%-5d %20s %s\n" `vm_val $vm ID` "$NAME" "$STATE"
-	done
-	cd $CPWD
-	;;
+    cd $BASE_DIR
+    printf "%-5s %20s %s\n" "ID" "VM" "Status"
+    for vm in `ls -1`;
+    do
+      NAME=`vm_val $vm NAME`
+      PID=`vm_status $NAME`
+      if [ -z "$PID" ]; then
+        STATE="ofline"
+      else
+        STATE="online ($PID)"
+      fi
+      ACTIVE=`vm_val $vm ACTIVE`
+      if [  "$ACTIVE" == 0 ]; then
+        STATE="inactive"
+      fi
+      printf "%-5d %20s %s\n" `vm_val $vm ID` "$NAME" "$STATE"
+  done
+  cd $CPWD
+  ;;
   stop) 
-		check_vm $2
-		NAME=`vm_val $2 NAME`
-		PID=`vm_status $NAME`
-		if [ -z "$PID" ]; then
-			echo "VM $NAME not running"
-		else
-			echo "VM $NAME stopping... ($PID)"
-			kill $PID
-		fi
-	;;
+    check_vm $2
+    NAME=`vm_val $2 NAME`
+    PID=`vm_status $NAME`
+    if [ -z "$PID" ]; then
+      echo "VM $NAME not running"
+    else
+      echo "VM $NAME stopping... ($PID)"
+      kill $PID
+    fi
+  ;;
   set)
-		cehck_vm $2
-		set_opt "$2" "$3" "$4" "$5" "$6"
-	;;
-	new)
-	  new_vm $2	
-	;;
-	activate)
-		cehck_vm $2
-		set_opt $2 "active" "1"
-		echo "VM $2 activated."
-	;;
-	deactivate)
-		cehck_vm $2
-		set_opt $2 "active" "0"
-		echo "VM $2 deactivated."
-	;;
-	show)
-		check_vm $2
-		show_vm $2	
-	;;
+    check_vm $2
+    set_opt "$2" "$3" "$4" "$5" "$6"
+  ;;
+  new)
+    new_vm $2  
+  ;;
+  activate)
+    check_vm $2
+    set_opt $2 "active" "1"
+    echo "VM $2 activated."
+  ;;
+  deactivate)
+    check_vm $2
+    set_opt $2 "active" "0"
+    echo "VM $2 deactivated."
+  ;;
+  show)
+    check_vm $2
+    show_vm $2  
+  ;;
   *)
-	cat <<-EOH
+  cat <<-EOH
   main commands
   kvmadm list            - list all VM's
   kvmadm show <vm>       - gives a detailed info over the VM
@@ -350,20 +350,19 @@ case $1 in
   set options
   cpu <v-cores>
   mem <MB>
-  iso <iso-file>
-  disk <disk in vm disks folder>
+  disk <id> type|file <value>
   net <network id> <type|vnic|vlan> <value>
   net <network id> <mac> <rand|value>
-	opts <opt string>
+  opts <opt string>
 
   Helpful hints
   =============
   Create a new virtual interface with this command:
   dladm create-vnic -l <interface> <virtual interface>
 
-	Create a new disk with this command:
-	zfs create -V 10g $VM_POOL/<disk name>
+  Create a new disk with this command:
+  zfs create -V 10g $VM_POOL/<disk name>
 EOH
-	;;
+  ;;
 esac
 exit 0
