* Added activate and deactivate. * Some improvements and fixes.

diff --git a/kvmadm b/kvmadm
--- a/kvmadm
+++ b/kvmadm
@@ -7,7 +7,7 @@ BASE_DIR=/etc/vms
 RUN_PATH=/tmp
 
 
-function new() {
+function new_vm() {
 	NAME=$1
 	if [ -f "$BASE_DIR/$NAME" ]; then
 		echo "VM $NAME already exists"
@@ -21,17 +21,19 @@ ISO=
 NIC0_VNIC=
 NIC0_MAC=$MAC
 MEM=
-NIC0_TYPE=e1000
+NIC0_TYPE=$NIC_TYPE
 ACTIVE=0
 ID=1
 CPUS=1
+OPTS=
 EOF
 }
+
 function start() {
 	VM=$1
 	STATUS=`vm_status $VM`
 	. $BASE_DIR/$VM
-	if [ "x$STATUS" != "x" ]; then
+	if [ -z "$STATUS" ]; then
 		echo "VM $NAME already running. $STATUS" 
 		exit 1
 	fi
@@ -43,15 +45,15 @@ function start() {
 	PARAMS="-enable-kvm -nographic -no-hpet -smp $CPUS"
 	PARAMS="${PARAMS} -monitor unix:${RUN_PATH}/kvm.${NAME}.mon,server,nowait"
 	NIC_ID=0 
-	while [ "$(eval echo "\${NIC${NIC_ID}_VNIC}")x" != "x" ]; do
+	while [ "$(eval echo "\${NIC${NIC_ID}_VNIC}")" ]; do
 		VNIC=$(eval echo "\${NIC${NIC_ID}_VNIC}")
 		MAC=$(eval echo "\${NIC${NIC_ID}_MAC}")
 		TYPE=$(eval echo "\${NIC${NIC_ID}_TYPE}")
-		if [ "${TYPE}x" == "x" ]; then
+		if [ -z "${TYPE}" ]; then
 			TYPE="virtio"
 		fi
 		VLAN=$(eval echo "\${NIC${NIC_ID}_VLAN}")
-		if [ "${VLAN}x" == "x" ]; then
+		if [ -z "${VLAN}" ]; then
 			VLAN="0"
 		fi
 		PARAMS="${PARAMS} -net nic,vlan=${VLAN},name=net${NIC_ID},model=${TYPE},macaddr=${MAC}"
@@ -59,19 +61,27 @@ function start() {
 		NIC_ID=`expr $NIC_ID + 1`
 	done
 	PARAMS="${PARAMS} -m ${MEM} -vnc :$ID  -no-hpet"
-	PARAMS="${PARAMS} -chardev socket,id=serial0,path=${RUN_PATH}/kvm.$NAME.console,server,nowait -serial chardev:serial0 -hdb $VMDISK_ROOT/$DISK"
+	PARAMS="${PARAMS} -chardev socket,id=serial0,path=${RUN_PATH}/kvm.$NAME.console,server,nowait -serial chardev:serial0 -hdb $VMDISK_ROOT/$DISK ${OPTS}"
 	qemu-system-x86_64 ${PARAMS} > ${RUN_PATH}/kvm.${NAME}.log &
 	echo $! > ${RUN_PATH}/kvm.${NAME}.pid
 }
 
-function replace_opt() {
-	sed -i "s/${2}=.*/${2}=${3}/" ${BASE_DIR}/${1}
+function write_opt() {
+	if [ -z "$3" ]; then
+		sed -i "s/^${2}=.*//" ${BASE_DIR}/${1}
+	else	
+		if grep "^${2}=" ${BASE_DIR}/${1} > /dev/null; then
+			sed -i "s/^${2}=.*/${2}=${3}/" ${BASE_DIR}/${1}
+		else
+			echo "${2}=${3}" >> ${BASE_DIR}/${1}
+		fi
+	fi
 }
 
 function vm_status() {
 	PID=`cat ${RUN_PATH}/kvm.${1}.pid 2> /dev/null`
 	LIST=`ps -e | grep "^[ ]*$PID "`
-	if [ "x$LIST" != "x" ]; then
+	if [ "$LIST"  ]; then
 		echo $PID
 	fi
 }
@@ -84,25 +94,35 @@ function vm_val() {
 
 function set_opt() {
 	VM=$1
+	if [ ! -f $BASE_DIR/$VM ]
+	then
+		echo "Can't find VM $MV_CFG_PATH"
+		exit 1
+	fi
 	OPT=$2
-	echo "$1 $2 $3 $4"
 	case $OPT in
+		opts)
+			write_opt $VM "OPTS" "$3"
+		;;
+		active)
+			write_opt $VM "ACTIVE" "$3"
+		;;
 		cpu)
-			replace_opt $VM "CPUS" "$3"
+			write_opt $VM "CPUS" "$3"
 		;;
 		mem)
-			replace_opt $VM "MEM" "$3"
+			write_opt $VM "MEM" "$3"
 		;;
 		disk)
 			if [ -f $VMDISK_ROOT/$3 ]; then
-				replace_opt $VM "DISK" "$3"
+				write_opt $VM "DISK" "$3"
 			else
 				echo "Can't find VM DISK $3"
 			fi
 		;;
 		iso)
 			if [ -f $3]; then
-				replace_opt $VM "ISO" "$3"
+				write_opt $VM "ISO" "$3"
 			else
 				echo "Can't find ISO file $3."
 			fi
@@ -110,16 +130,16 @@ function set_opt() {
 		net)
 			case $4 in
 				type)
-					replace_opt $VM "NIC${3}_TYPE" "$5"
+					write_opt $VM "NIC${3}_TYPE" "$5"
 				;;
 				vnic)
-					replace_opt $VM "NIC${3}_VNIC" "$5"
+					write_opt $VM "NIC${3}_VNIC" "$5"
 				;;
 				mac)
-					replace_opt $VM "NIC${3}_MAC" "$5"
+					write_opt $VM "NIC${3}_MAC" "$5"
 				;;
 				vlan)
-					replace_opt $VM "NIC${3}_VLAN" "$5"
+					write_opt $VM "NIC${3}_VLAN" "$5"
 				;;
 				*)
 					echo "Invalid network category, valid options are: type, vnic, mac, vlan."
@@ -175,21 +195,29 @@ case $1 in
 		fi
 	;;
   set)
-	if [ -f $BASE_DIR/$2 ]
-	then
-		set_opt $2 $3 $4 $5 $6
-	else
-		echo "Can't find VM $MV_CFG_PATH"
-		exit 1
-	fi
+		set_opt "$2" "$3" "$4" "$5" "$6"
+	;;
+	new)
+	  new_vm $2	
+	;;
+	activate)
+		set_opt $2 "active" "1"
+		echo "VM $2 activated."
+	;;
+	deactivate)
+		set_opt $2 "active" "0"
+		echo "VM $2 deactivated."
 	;;
   *)
 	cat <<-EOH
   main commands
-  vmadm list       - list all VM's
-  vmadm start <vm> - starts a powered off VM
-  vmadm stop <vm>  - stops a running VM
-  vmadm set <vm>   - sets options for a VM
+  kvmadm list            - list all VM's
+  kvmadm start <vm>      - starts a powered off VM
+  kvmadm stop <vm>       - stops a running VM
+  kvmadm set <vm>        - sets options for a VM
+  kvmadm new <vm>        - creates a new VM
+  kvmadm activate <vm>   - activates the VM
+  kvmadm deactivate <vm> - activates the VM
   
   set options
   cpu <v-cores>
@@ -197,6 +225,7 @@ case $1 in
   iso <iso-file>
   disk <disk in vm disks folder>
   net <network id> <type|vnic|mac|vlan> <value>
+	opts <opt string>
 
   Helpful hints
   =============
